name: motor_sport_calendar
description: A modern, multi-series motorsport calendar.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/data/f1/2026/
    - assets/data/f1/2026/events/
    - assets/data/f2/2026/
    - assets/data/f2/2026/events/
    - assets/data/f3/2026/
    - assets/data/f3/2026/events/
    - assets/data/imsa/2026/
    - assets/data/imsa/2026/events/
    - assets/data/indycar/2026/
    - assets/data/indycar/2026/events/
    - assets/data/indynxt/2026/
    - assets/data/indynxt/2026/events/
    - assets/data/wec/2026/
    - assets/data/wec/2026/events/
    - assets/circuits/
    - assets/brands/
